"""App profile YAML lifecycle — load, save, merge, and lookup.

The profile lives at {repo_path}/.apptest/app-profile.yml and has two layers:
  - auto:      machine-maintained, regenerated by `apptest init` and updated by `analyze`
  - overrides: human-curated, never auto-modified
"""

from datetime import datetime, timezone
from pathlib import Path

import yaml


_PROFILE_DIR = ".apptest"
_PROFILE_FILENAME = "app-profile.yml"

_OVERRIDES_TEMPLATE = """\
# overrides:
#   reclassify:
#     - file: "app/src/main/java/com/example/CustomView.kt"
#       screen_type: "compose_screen"
#   ignore:
#     - "app/src/main/java/com/example/DebugActivity.kt"
#   extra_screens:
#     - name: "SettingsScreen"
#       file: "app/src/main/java/com/example/SettingsComposable.kt"
#       type: "composable"
"""


def _profile_path(repo_path: str | Path) -> Path:
    return Path(repo_path) / _PROFILE_DIR / _PROFILE_FILENAME


def load_profile(repo_path: str | Path) -> dict | None:
    """Load the raw profile YAML. Returns None if the file doesn't exist."""
    path = _profile_path(repo_path)
    if not path.exists():
        return None
    with open(path) as f:
        data = yaml.safe_load(f)
    return data if isinstance(data, dict) else None


def load_effective_profile(repo_path: str | Path) -> dict | None:
    """Load profile and merge auto + overrides into a single effective view.

    Override rules:
      - reclassify: change screen_type for matching files
      - ignore: remove screens/chains matching listed file paths
      - extra_screens: append additional screen entries
    """
    profile = load_profile(repo_path)
    if profile is None:
        return None

    auto = profile.get("auto", {})
    overrides = profile.get("overrides", {})
    if not overrides:
        return profile

    # Deep copy auto section to avoid mutating the original
    import copy
    effective_auto = copy.deepcopy(auto)

    # Apply reclassify
    reclassify_map: dict[str, str] = {}
    for entry in overrides.get("reclassify", []):
        if "file" in entry and "screen_type" in entry:
            reclassify_map[entry["file"]] = entry["screen_type"]

    if reclassify_map:
        for screen in effective_auto.get("screens", []):
            if screen.get("file") in reclassify_map:
                screen["type"] = reclassify_map[screen["file"]]

    # Apply ignore
    ignore_set = set(overrides.get("ignore", []))
    if ignore_set:
        effective_auto["screens"] = [
            s for s in effective_auto.get("screens", [])
            if s.get("file") not in ignore_set
        ]
        effective_auto["chains"] = [
            c for c in effective_auto.get("chains", [])
            if c.get("screen_file") not in ignore_set
        ]

    # Apply extra_screens
    for extra in overrides.get("extra_screens", []):
        effective_auto.setdefault("screens", []).append(extra)

    profile_copy = dict(profile)
    profile_copy["auto"] = effective_auto
    return profile_copy


def save_profile(repo_path: str | Path, profile: dict) -> Path:
    """Write the profile YAML, creating the .apptest directory if needed.

    Appends a commented overrides template if no overrides section exists.
    """
    path = _profile_path(repo_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    # Set timestamp
    profile.setdefault("auto", {})["updated_at"] = (
        datetime.now(timezone.utc).isoformat(timespec="seconds")
    )

    content = yaml.dump(profile, default_flow_style=False, sort_keys=False)

    if "overrides" not in profile:
        content += "\n" + _OVERRIDES_TEMPLATE

    with open(path, "w") as f:
        f.write(content)

    return path


def lookup_affected_screens(file_path: str, profile: dict) -> list[dict]:
    """Fast chain lookup: find screens affected by a changed file.

    Searches the profile's chains for entries where the file_path (or its
    class name) appears in the chain members. Returns matching screen info
    with chain and confidence.
    """
    auto = profile.get("auto", {})
    chains = auto.get("chains", [])
    class_name = Path(file_path).stem

    results: list[dict] = []
    seen_screens: set[str] = set()

    for chain in chains:
        members = chain.get("members", [])
        # Check if this file is in the chain (by path or class name)
        matched = False
        for member in members:
            if isinstance(member, str):
                if member == file_path or Path(member).stem == class_name:
                    matched = True
                    break
            elif isinstance(member, dict):
                if member.get("file") == file_path or member.get("class") == class_name:
                    matched = True
                    break

        if matched:
            screen_file = chain.get("screen_file", "")
            if screen_file and screen_file not in seen_screens:
                seen_screens.add(screen_file)
                results.append({
                    "screen_file": screen_file,
                    "screen_name": chain.get("screen_name", Path(screen_file).stem),
                    "chain": members,
                    "confidence": chain.get("confidence", "medium"),
                })

    return results


def resolve_screen_file(screen_name: str, profile: dict) -> str | None:
    """Map a screen name (e.g. 'SearchFragment') to its file path via the profile."""
    auto = profile.get("auto", {})
    for screen in auto.get("screens", []):
        if screen.get("name") == screen_name:
            return screen.get("file")
    return None
